<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <fieldset>
        <legend>Connexion</legend>
        <form action="" method="POST">
            <label for="fname">Nom</label>
            <input type="text" name="fname" id="fname" >
            <label for="lname">Prénoms</label>
            <input type="text" name="lname" id="lname">
            <label for="pseudo">login</label>
            <input type="text" name="pseudo" id="pseudo">
            <label for="password">Creer un mot de passe</label>
            <input type="password" name="password" id="password">
            <label for="ConfPassword">Confirmer un mot de passe</label>
            <input type="password" name="ConfPassword" id="Confpassword">
            <button type="submit">Inscription</button>
        </form>
    </fieldset>
</body>
</html>